spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_oj
    hikari:
      username: root
      password: mysql
    dirver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true